### ISSUE TITLE
Deposits/Withdrawals history

### ISSUE THREAD

**Issue by adelineu** [bitmartexchange/bitmart-official-api-docs#14]
Hello,

Does bitmart provide endpoints for retrieving deposits and withdrawals?
We have an ongoing project that's integrated with your api and having a way to retrieve this information would help.

Thank you.

**Comment by 11101171** [comment]
Hi,
We now have a new version of THE API interface, please check the link https://developer-pro.bitmart.com. the recharge and withdrawal function is also in our plan, but let me be clear, this is only available on the new version.
