### ISSUE TITLE
Any plan to support Real-time trading pair info through websocket?

### ISSUE THREAD

**Issue by YushengLi** [bitmartexchange/bitmart-official-api-docs#2]
There are some differences between `Realtime trading pair info` (Over REST API) and `Real-time trading info`(Over Websocket)

### REST API
```json
{
   "priceChange":"0%",
   "symbolId":22,
   "ask_1":"0.004811",
   "anchorId":16,
   "anchorName":"ETH",
   "pair":"BMX_ETH",
   "url":"https://www.bitmart.com/trade.html?symbol=22",
   "volume":"560356.868000",
   "coinId":18,
   "high_24h":"0.004811",
   "low_24h":"0.004811",
   "new_24h":"0.004811",
   "closeTime":1526047727412,
   "bid_1":"0.004811",
   "coinName":"BMX",
   "baseVolume":"2542.024679",
   "openTime":1525961327412,
   "depthStartPrecision": 4,
   "depthEndPrecision": 6
}
```

### Websocket API
```
{
  "subscribe":"price",
  "symbol": 22,
  "local": "en_US",
  "data":{
    "o":"0.0000100",
    "h":"0.0000100",
    "l":"0.0000100",
    "v":"0.0000100",
    "c":"0.0000100",
    "increase":"1",
    "fluctuation":"-0.05",
    "rate":"0",
    "sign":"USD"
  }
}
```

Is there any plan to support more details info (Such as Realtime Ask, Bid) over Websocket API?

Also, I'm curious whether there's any Rate LIMIT of the REST API?

**Comment by siyuan1992** [comment]
The trade channel has both level 1 (bid1, ask1) and level 2 information.

Rate limit depends on different endpoints, especially for placing orders. We recommend to call it within 5 times per minute or use websocket to check the market information.

There was an issue in ws and it should be fixed. Could you check it again? Thanks for reaching out

**Comment by YushengLi** [comment]
Seems that these documentation is deprecated in favor of new documents drafted a day ago at 
https://github.com/bitmartexchange/api-docs, I'll close this issue and open and new one there.
